#+HUGO_BASE_DIR: ~/Coding/test_site/
#+HUGO_SECTION: notes/
* DONE Life hacks                                                    :@notes:
  CLOSED: [2019-06-24 Mon 21:57]
  :PROPERTIES:
  :EXPORT_FILE_NAME: lifehacking
  :EXPORT_DATE: 2019-06-24
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :description "Reverse engineering social situations"
  :END:

Below is a collection of life hacks that I have been using over the years.

** Name resolution

> In a situation, where you will be identified by your name, give a purposefully
unique name. 

Having a name that stands out a) minimises the risk of a "hash
collision", where you are confused for someone else, b) makes it memorable.

When I book tables in restaurants or arrange pick ups, I do it under the name
"Boutros" (after [[https://en.wikipedia.org/wiki/Boutros_Boutros-Ghali][Boutros Boutros-Ghali]]). This makes it easier for people to find
my name on the list.

In a place, where I regularly grab lunch people know me as Boutros,
which makes it effortless to order and collect. They even greet me "by name", when I walk in.

** Crowdsourcing opinions

> In the absence of a tripadvisor-like forum for people to review products and
services, find a group of users/customers and write to them directly.

As a teenager I was lucky enough for my parents to /spoil/ me with summer camps.
One summer, I had to find a camp in Spain. I wanted to find a camp with a) good
quality tuition b) a balanced international group c) fun sport activities. There
were no review websites outside the small "testimonials" section on the website
and the pages for each camp didn't list their timetable of activities.

At the time, it was common for people to create facebook groups after shared
experiences like summer camps. I found facebook groups from previous summers at
the camps I was interested in. Using a template, I messaged a dozen people
asking about their experiences at the camps and what facilities/activities were
available.

This enabled me to choose a camp with basketball and a fun group of people. 

I thought it was a logical thing to do, however, several people have since told me 
it was "out of the box".
