
Had an interesting conversation with a stranger recently, who made me think about what it means to seem smart to someone. 

** The importance of smarts

"Smart" is an property that is poorly defined, yet sought after from young age onwards. 

Dating, choosing friends, hiring and other times in life when people choose their group belonging, they often prioritise "being around smart people". 

I don't agree with two things: the blind reliance on smarts regardless 

** Being abstract as a way to seem smart

   The quote below is often attributed to Eleanor Roosevelt. 
   
#+BEGIN_QUOTE
Great minds discuss ideas; average minds discuss events; small minds discuss people
#+END_QUOTE

Talking about people (celebrities, friends or relatives) gives people the opportunity to express themselves by saying something about that person.

A conversation about an event  

  Discussing ideas has the greatest surface area of opportunity for your interlocutor to connect his experience and thoughts with what you are saying. 

Therefore, when you discuss ideas 
